# Generated by Django 4.2.1 on 2024-02-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=30, unique=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='unloadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloadTypeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=30)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.origin')),
                ('unloadType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.unloadtype')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.origin')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.species')),
                ('unloadType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.unloadtype')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.vessel')),
            ],
        ),
    ]
