# Generated by Django 4.2.2 on 2023-07-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Origin",
            fields=[
                (
                    "origin",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "species_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("species_name", models.CharField(max_length=30)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("user_type", models.CharField(max_length=30)),
                ("user_id", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vessel_id", models.CharField(max_length=30)),
                ("vessel_name", models.CharField(max_length=30)),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Analytics.origin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=30)),
                ("date", models.DateTimeField()),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Analytics.origin",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Analytics.species",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Analytics.users",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Analytics.vessel",
                    ),
                ),
            ],
        ),
    ]
