# Generated by Django 4.2.1 on 2023-07-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('origin', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=30)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.origin')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.origin')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.species')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.vessel')),
            ],
        ),
    ]
