# Generated by Django 4.2.2 on 2023-07-11 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
