# Generated by Django 4.2.1 on 2024-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
