# Generated by Django 4.2.1 on 2023-11-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='price',
        ),
    ]
