# Generated by Django 4.2.1 on 2023-07-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
