# Generated by Django 4.2.1 on 2024-02-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_alter_species_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
