# Generated by Django 4.2.1 on 2023-11-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_remove_species_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytransaction',
            name='price',
        ),
    ]
