# Generated by Django 4.2.1 on 2024-02-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_alter_species_species_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytransaction',
            name='percentage',
        ),
    ]
