# Generated by Django 4.2.1 on 2023-12-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_province_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='City',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.city'),
        ),
        migrations.AddField(
            model_name='origin',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='origin',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
