# Generated by Django 4.2.1 on 2023-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_alter_dailytransaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='id',
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
