# Generated by Django 4.2.1 on 2023-12-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0005_origin_city_origin_percentage_origin_volume'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='origin',
            unique_together={('origin', 'date', 'City', 'volume', 'percentage')},
        ),
    ]
