# Generated by Django 4.2.1 on 2023-12-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0006_alter_origin_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='unloadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloadTypeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='origin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='origin',
            name='unloadType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.unloadtype'),
        ),
    ]
