# Generated by Django 4.2.1 on 2024-01-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0008_remove_origin_percentage_remove_origin_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origin',
            name='unloadType',
        ),
        migrations.AddField(
            model_name='vessel',
            name='unloadType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.unloadtype'),
        ),
    ]
