# Generated by Django 4.2.1 on 2024-01-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0009_remove_origin_unloadtype_vessel_unloadtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytransaction',
            name='unloadType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Analytics.unloadtype'),
        ),
    ]
