# Generated by Django 4.2.1 on 2024-01-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0011_alter_species_species_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origin',
            name='City',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
